name: Ejecutar Programa C++ en Windows

on: [push]

jobs:
  ejecutar_programa:
    runs-on: windows-latest

    steps:
    - name: Configurar el entorno
      run: choco install mingw -y
      shell: powershell

    - name: Clonar el repositorio
      run: git clone https://github.com/saulish/Paginacion-algoritmo.git

    - name: Compilar y ejecutar
      run: |
        cd Paginacion-algoritmo
        g++ -o ejecutable main.cpp
        RefreshEnv
        .\ejecutable.exe
      shell: powershell

