name: Ejecutar Programa C++

on: [push]

jobs:
  ejecutar_programa:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar el entorno
      uses: actions/setup-node@v2

    - name: Clonar el repositorio
      run: git clone https://github.com/saulish/Paginacion-algoritmo.git

    - name: Compilar y ejecutar
      run: |
        cd Paginacion-algoritmo
        g++ -o ejecutable main.cpp
        ./ejecutable
